# fly.toml app configuration file generated for e-restore on 2023-08-26T12:36:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "e-restore"
primary_region = "yyz"

[build]
  image = "akibanwar/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishedKey="pk_test_51Nj2yxBsyDyEwbCREs1MqDnSMUYaprfeklTfJIljmzrNgM5VspTfJ0cKIBdF6eKNFgPJqCso4vPZBmGJf5gzH69W00boY48M6a"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
